//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 10:11:20 AM CET 
//


package com.tibco.xmlns.authentication;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Type that all AuthenticationConfigurations must be defined as.
 * 
 * <p>Java class for AuthenticationConfigurationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AuthenticationConfigurationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="configName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="configDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="idleTimeout" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="wrapperAuthenticationPlugInClassName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuthenticationConfigurationType", propOrder = {
    "configName",
    "configDescription",
    "idleTimeout",
    "wrapperAuthenticationPlugInClassName"
})
@XmlSeeAlso({
    WebServerAuthenticationConfiguration.class,
    CredentialAuthenticationConfigurationType.class
})
public class AuthenticationConfigurationType {

    @XmlElement(required = true)
    protected String configName;
    protected String configDescription;
    protected int idleTimeout;
    protected String wrapperAuthenticationPlugInClassName;

    /**
     * Gets the value of the configName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * Sets the value of the configName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigName(String value) {
        this.configName = value;
    }

    /**
     * Gets the value of the configDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigDescription() {
        return configDescription;
    }

    /**
     * Sets the value of the configDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigDescription(String value) {
        this.configDescription = value;
    }

    /**
     * Gets the value of the idleTimeout property.
     * 
     */
    public int getIdleTimeout() {
        return idleTimeout;
    }

    /**
     * Sets the value of the idleTimeout property.
     * 
     */
    public void setIdleTimeout(int value) {
        this.idleTimeout = value;
    }

    /**
     * Gets the value of the wrapperAuthenticationPlugInClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWrapperAuthenticationPlugInClassName() {
        return wrapperAuthenticationPlugInClassName;
    }

    /**
     * Sets the value of the wrapperAuthenticationPlugInClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWrapperAuthenticationPlugInClassName(String value) {
        this.wrapperAuthenticationPlugInClassName = value;
    }

}
