//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 10:11:20 AM CET 
//


package com.tibco.xmlns.authentication;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tibco.xmlns.authentication package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CookieAuthenticationConfiguration_QNAME = new QName("http://www.tibco.com/xmlns/authentication", "CookieAuthenticationConfiguration");
    private final static QName _URLAuthenticationConfiguration_QNAME = new QName("http://www.tibco.com/xmlns/authentication", "URLAuthenticationConfiguration");
    private final static QName _RequiresAuthentication_QNAME = new QName("http://www.tibco.com/xmlns/authentication", "RequiresAuthentication");
    private final static QName _WebServerAuthenticationConfiguration_QNAME = new QName("http://www.tibco.com/xmlns/authentication", "WebServerAuthenticationConfiguration");
    private final static QName _HttpSessionAuthenticationConfiguration_QNAME = new QName("http://www.tibco.com/xmlns/authentication", "HttpSessionAuthenticationConfiguration");
    private final static QName _CustomAuthenticationConfiguration_QNAME = new QName("http://www.tibco.com/xmlns/authentication", "CustomAuthenticationConfiguration");
    private final static QName _AuthenticationConfiguration_QNAME = new QName("http://www.tibco.com/xmlns/authentication", "AuthenticationConfiguration");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tibco.xmlns.authentication
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HttpSessionAuthenticationConfiguration }
     * 
     */
    public HttpSessionAuthenticationConfiguration createHttpSessionAuthenticationConfiguration() {
        return new HttpSessionAuthenticationConfiguration();
    }

    /**
     * Create an instance of {@link CredentialAuthenticationConfigurationType }
     * 
     */
    public CredentialAuthenticationConfigurationType createCredentialAuthenticationConfigurationType() {
        return new CredentialAuthenticationConfigurationType();
    }

    /**
     * Create an instance of {@link URLAuthenticationConfiguration }
     * 
     */
    public URLAuthenticationConfiguration createURLAuthenticationConfiguration() {
        return new URLAuthenticationConfiguration();
    }

    /**
     * Create an instance of {@link WebServerAuthenticationConfiguration }
     * 
     */
    public WebServerAuthenticationConfiguration createWebServerAuthenticationConfiguration() {
        return new WebServerAuthenticationConfiguration();
    }

    /**
     * Create an instance of {@link AuthenticationConfigurationType }
     * 
     */
    public AuthenticationConfigurationType createAuthenticationConfigurationType() {
        return new AuthenticationConfigurationType();
    }

    /**
     * Create an instance of {@link CookieAuthenticationConfiguration }
     * 
     */
    public CookieAuthenticationConfiguration createCookieAuthenticationConfiguration() {
        return new CookieAuthenticationConfiguration();
    }

    /**
     * Create an instance of {@link RequiresAuthentication }
     * 
     */
    public RequiresAuthentication createRequiresAuthentication() {
        return new RequiresAuthentication();
    }

    /**
     * Create an instance of {@link CustomAuthenticationConfiguration }
     * 
     */
    public CustomAuthenticationConfiguration createCustomAuthenticationConfiguration() {
        return new CustomAuthenticationConfiguration();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CookieAuthenticationConfiguration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/authentication", name = "CookieAuthenticationConfiguration", substitutionHeadNamespace = "http://www.tibco.com/xmlns/authentication", substitutionHeadName = "AuthenticationConfiguration")
    public JAXBElement<CookieAuthenticationConfiguration> createCookieAuthenticationConfiguration(CookieAuthenticationConfiguration value) {
        return new JAXBElement<CookieAuthenticationConfiguration>(_CookieAuthenticationConfiguration_QNAME, CookieAuthenticationConfiguration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link URLAuthenticationConfiguration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/authentication", name = "URLAuthenticationConfiguration", substitutionHeadNamespace = "http://www.tibco.com/xmlns/authentication", substitutionHeadName = "AuthenticationConfiguration")
    public JAXBElement<URLAuthenticationConfiguration> createURLAuthenticationConfiguration(URLAuthenticationConfiguration value) {
        return new JAXBElement<URLAuthenticationConfiguration>(_URLAuthenticationConfiguration_QNAME, URLAuthenticationConfiguration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequiresAuthentication }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/authentication", name = "RequiresAuthentication", substitutionHeadNamespace = "http://www.tibco.com/xmlns/dd", substitutionHeadName = "DeploymentDescriptor")
    public JAXBElement<RequiresAuthentication> createRequiresAuthentication(RequiresAuthentication value) {
        return new JAXBElement<RequiresAuthentication>(_RequiresAuthentication_QNAME, RequiresAuthentication.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WebServerAuthenticationConfiguration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/authentication", name = "WebServerAuthenticationConfiguration", substitutionHeadNamespace = "http://www.tibco.com/xmlns/authentication", substitutionHeadName = "AuthenticationConfiguration")
    public JAXBElement<WebServerAuthenticationConfiguration> createWebServerAuthenticationConfiguration(WebServerAuthenticationConfiguration value) {
        return new JAXBElement<WebServerAuthenticationConfiguration>(_WebServerAuthenticationConfiguration_QNAME, WebServerAuthenticationConfiguration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HttpSessionAuthenticationConfiguration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/authentication", name = "HttpSessionAuthenticationConfiguration", substitutionHeadNamespace = "http://www.tibco.com/xmlns/authentication", substitutionHeadName = "AuthenticationConfiguration")
    public JAXBElement<HttpSessionAuthenticationConfiguration> createHttpSessionAuthenticationConfiguration(HttpSessionAuthenticationConfiguration value) {
        return new JAXBElement<HttpSessionAuthenticationConfiguration>(_HttpSessionAuthenticationConfiguration_QNAME, HttpSessionAuthenticationConfiguration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomAuthenticationConfiguration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/authentication", name = "CustomAuthenticationConfiguration", substitutionHeadNamespace = "http://www.tibco.com/xmlns/authentication", substitutionHeadName = "AuthenticationConfiguration")
    public JAXBElement<CustomAuthenticationConfiguration> createCustomAuthenticationConfiguration(CustomAuthenticationConfiguration value) {
        return new JAXBElement<CustomAuthenticationConfiguration>(_CustomAuthenticationConfiguration_QNAME, CustomAuthenticationConfiguration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenticationConfigurationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/authentication", name = "AuthenticationConfiguration")
    public JAXBElement<AuthenticationConfigurationType> createAuthenticationConfiguration(AuthenticationConfigurationType value) {
        return new JAXBElement<AuthenticationConfigurationType>(_AuthenticationConfiguration_QNAME, AuthenticationConfigurationType.class, null, value);
    }

}
