//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 10:11:20 AM CET 
//


package com.tibco.xmlns.applicationmanagement.bw;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tibco.xmlns.applicationmanagement.bw package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Checkpoint_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement/BW", "checkpoint");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tibco.xmlns.applicationmanagement.bw
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Bwprocesses }
     * 
     */
    public Bwprocesses createBwprocesses() {
        return new Bwprocesses();
    }

    /**
     * Create an instance of {@link Bwprocess }
     * 
     */
    public Bwprocess createBwprocess() {
        return new Bwprocess();
    }

    /**
     * Create an instance of {@link Checkpoints }
     * 
     */
    public Checkpoints createCheckpoints() {
        return new Checkpoints();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement/BW", name = "checkpoint")
    public JAXBElement<String> createCheckpoint(String value) {
        return new JAXBElement<String>(_Checkpoint_QNAME, String.class, null, value);
    }

}
