//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 10:11:20 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tibco.com/xmlns/ApplicationManagement/BW",
									 xmlns={@XmlNs(namespaceURI = "http://www.tibco.com/xmlns/ApplicationManagement", prefix = ""),
			   								@XmlNs(namespaceURI = "http://www.tibco.com/xmlns/dd", prefix = "dd"),
			   								@XmlNs(namespaceURI = "http://www.tibco.com/xmlns/ApplicationManagement/BW", prefix = "bw"),
			   								@XmlNs(namespaceURI = "http://www.tibco.com/xmlns/authentication", prefix = "auth")},
			   						elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tibco.xmlns.applicationmanagement.bw;
import javax.xml.bind.annotation.XmlNs;
