//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 10:11:20 AM CET 
//


package com.tibco.xmlns.applicationmanagement;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BWServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BWServiceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.tibco.com/xmlns/ApplicationManagement}ServiceType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.tibco.com/xmlns/ApplicationManagement/BW}bwprocesses" minOccurs="0"/>
 *         &lt;element ref="{http://www.tibco.com/xmlns/ApplicationManagement/BW}checkpoints" minOccurs="0"/>
 *         &lt;element ref="{http://www.tibco.com/xmlns/ApplicationManagement}bwprocesses" minOccurs="0"/>
 *         &lt;element ref="{http://www.tibco.com/xmlns/ApplicationManagement}checkpoints" minOccurs="0"/>
 *         &lt;element ref="{http://www.tibco.com/xmlns/ApplicationManagement}isFt" minOccurs="0"/>
 *         &lt;element ref="{http://www.tibco.com/xmlns/ApplicationManagement}faultTolerant" minOccurs="0"/>
 *         &lt;element ref="{http://www.tibco.com/xmlns/ApplicationManagement}plugins" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BWServiceType", propOrder = {
    "rest"
})
@XmlSeeAlso({
    Bw.class,
    FormFlow.class
})
public class BWServiceType
    extends ServiceType
{

    @XmlElementRefs({
        @XmlElementRef(name = "checkpoints", namespace = "http://www.tibco.com/xmlns/ApplicationManagement", type = com.tibco.xmlns.applicationmanagement.Checkpoints.class),
        @XmlElementRef(name = "checkpoints", namespace = "http://www.tibco.com/xmlns/ApplicationManagement/BW", type = com.tibco.xmlns.applicationmanagement.bw.Checkpoints.class),
        @XmlElementRef(name = "isFt", namespace = "http://www.tibco.com/xmlns/ApplicationManagement", type = JAXBElement.class),
        @XmlElementRef(name = "faultTolerant", namespace = "http://www.tibco.com/xmlns/ApplicationManagement", type = FaultTolerant.class),
        @XmlElementRef(name = "bwprocesses", namespace = "http://www.tibco.com/xmlns/ApplicationManagement/BW", type = com.tibco.xmlns.applicationmanagement.bw.Bwprocesses.class),
        @XmlElementRef(name = "bwprocesses", namespace = "http://www.tibco.com/xmlns/ApplicationManagement", type = com.tibco.xmlns.applicationmanagement.Bwprocesses.class),
        @XmlElementRef(name = "plugins", namespace = "http://www.tibco.com/xmlns/ApplicationManagement", type = Plugins.class)
    })
    protected List<Object> rest;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Bwprocesses" is used by two different parts of a schema. See: 
     * line 67 of file:/C:/temp/tibco_xsd/ApplicationManagement.xsd
     * line 65 of file:/C:/temp/tibco_xsd/ApplicationManagement.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the rest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.tibco.xmlns.applicationmanagement.Checkpoints }
     * {@link com.tibco.xmlns.applicationmanagement.bw.Checkpoints }
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link FaultTolerant }
     * {@link com.tibco.xmlns.applicationmanagement.bw.Bwprocesses }
     * {@link com.tibco.xmlns.applicationmanagement.Bwprocesses }
     * {@link Plugins }
     * 
     * 
     */
    public List<Object> getRest() {
        if (rest == null) {
            rest = new ArrayList<Object>();
        }
        return this.rest;
    }

}
