//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 10:11:20 AM CET 
//


package com.tibco.xmlns.applicationmanagement;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tibco.xmlns.applicationmanagement package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PerformPolicy_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "performPolicy");
    private final static QName _NameValuePairInteger_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "NameValuePairInteger");
    private final static QName _Container_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "container");
    private final static QName _Machine_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "machine");
    private final static QName _FormFlow_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "formFlow");
    private final static QName _HttpRepoInstance_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "httpRepoInstance");
    private final static QName _EmailAction_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "emailAction");
    private final static QName _Action_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "action");
    private final static QName _NameValuePairBoolean_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "NameValuePairBoolean");
    private final static QName _RemoteRepoInstance_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "remoteRepoInstance");
    private final static QName _Level_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "level");
    private final static QName _Event_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "event");
    private final static QName _Bw_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "bw");
    private final static QName _NVPair_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "NVPair");
    private final static QName _FailureEvent_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "failureEvent");
    private final static QName _SuspendProcessEvent_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "suspendProcessEvent");
    private final static QName _CustomAction_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "customAction");
    private final static QName _Service_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "service");
    private final static QName _CheckPointRecoveryStorage_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "checkPointRecoveryStorage");
    private final static QName _LogEvent_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "logEvent");
    private final static QName _Checkpoint_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "checkpoint");
    private final static QName _Im_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "im");
    private final static QName _Adapter_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "adapter");
    private final static QName _NameValuePair_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "NameValuePair");
    private final static QName _BaseService_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "baseService");
    private final static QName _RvRepoInstance_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "rvRepoInstance");
    private final static QName _Application_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "application");
    private final static QName _IsFt_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "isFt");
    private final static QName _NameValuePairPassword_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "NameValuePairPassword");
    private final static QName _LocalRepoInstance_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "localRepoInstance");
    private final static QName _RepoInstance_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "repoInstance");
    private final static QName _StartupType_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "startupType");
    private final static QName _AlertAction_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "alertAction");
    private final static QName _PluginsExtends_QNAME = new QName("http://www.tibco.com/xmlns/ApplicationManagement", "extends");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tibco.xmlns.applicationmanagement
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Authentications }
     * 
     */
    public Authentications createAuthentications() {
        return new Authentications();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link NVPairs }
     * 
     */
    public NVPairs createNVPairs() {
        return new NVPairs();
    }

    /**
     * Create an instance of {@link ApplicationType }
     * 
     */
    public ApplicationType createApplicationType() {
        return new ApplicationType();
    }

    /**
     * Create an instance of {@link ActionType }
     * 
     */
    public ActionType createActionType() {
        return new ActionType();
    }

    /**
     * Create an instance of {@link Events }
     * 
     */
    public Events createEvents() {
        return new Events();
    }

    /**
     * Create an instance of {@link FaultTolerant }
     * 
     */
    public FaultTolerant createFaultTolerant() {
        return new FaultTolerant();
    }

    /**
     * Create an instance of {@link NVPairType }
     * 
     */
    public NVPairType createNVPairType() {
        return new NVPairType();
    }

    /**
     * Create an instance of {@link RepoInstances }
     * 
     */
    public RepoInstances createRepoInstances() {
        return new RepoInstances();
    }

    /**
     * Create an instance of {@link EmailAction }
     * 
     */
    public EmailAction createEmailAction() {
        return new EmailAction();
    }

    /**
     * Create an instance of {@link FailureEvent }
     * 
     */
    public FailureEvent createFailureEvent() {
        return new FailureEvent();
    }

    /**
     * Create an instance of {@link AnyObject }
     * 
     */
    public AnyObject createAnyObject() {
        return new AnyObject();
    }

    /**
     * Create an instance of {@link Im }
     * 
     */
    public Im createIm() {
        return new Im();
    }

    /**
     * Create an instance of {@link NameValuePair }
     * 
     */
    public NameValuePair createNameValuePair() {
        return new NameValuePair();
    }

    /**
     * Create an instance of {@link Monitor }
     * 
     */
    public Monitor createMonitor() {
        return new Monitor();
    }

    /**
     * Create an instance of {@link NameValuePairPassword }
     * 
     */
    public NameValuePairPassword createNameValuePairPassword() {
        return new NameValuePairPassword();
    }

    /**
     * Create an instance of {@link Services }
     * 
     */
    public Services createServices() {
        return new Services();
    }

    /**
     * Create an instance of {@link Rulebases }
     * 
     */
    public Rulebases createRulebases() {
        return new Rulebases();
    }

    /**
     * Create an instance of {@link HttpRepoInstance }
     * 
     */
    public HttpRepoInstance createHttpRepoInstance() {
        return new HttpRepoInstance();
    }

    /**
     * Create an instance of {@link Setting.Java }
     * 
     */
    public Setting.Java createSettingJava() {
        return new Setting.Java();
    }

    /**
     * Create an instance of {@link Shutdown }
     * 
     */
    public Shutdown createShutdown() {
        return new Shutdown();
    }

    /**
     * Create an instance of {@link RepoInstanceType }
     * 
     */
    public RepoInstanceType createRepoInstanceType() {
        return new RepoInstanceType();
    }

    /**
     * Create an instance of {@link LogEvent }
     * 
     */
    public LogEvent createLogEvent() {
        return new LogEvent();
    }

    /**
     * Create an instance of {@link Setting }
     * 
     */
    public Setting createSetting() {
        return new Setting();
    }

    /**
     * Create an instance of {@link Bindings }
     * 
     */
    public Bindings createBindings() {
        return new Bindings();
    }

    /**
     * Create an instance of {@link NameValuePairInteger }
     * 
     */
    public NameValuePairInteger createNameValuePairInteger() {
        return new NameValuePairInteger();
    }

    /**
     * Create an instance of {@link Bwprocesses }
     * 
     */
    public Bwprocesses createBwprocesses() {
        return new Bwprocesses();
    }

    /**
     * Create an instance of {@link RvRepoInstance }
     * 
     */
    public RvRepoInstance createRvRepoInstance() {
        return new RvRepoInstance();
    }

    /**
     * Create an instance of {@link ServiceType }
     * 
     */
    public ServiceType createServiceType() {
        return new ServiceType();
    }

    /**
     * Create an instance of {@link Rulebases.Rulebase }
     * 
     */
    public Rulebases.Rulebase createRulebasesRulebase() {
        return new Rulebases.Rulebase();
    }

    /**
     * Create an instance of {@link Actions }
     * 
     */
    public Actions createActions() {
        return new Actions();
    }

    /**
     * Create an instance of {@link CustomAction }
     * 
     */
    public CustomAction createCustomAction() {
        return new CustomAction();
    }

    /**
     * Create an instance of {@link BWServiceType }
     * 
     */
    public BWServiceType createBWServiceType() {
        return new BWServiceType();
    }

    /**
     * Create an instance of {@link Binding }
     * 
     */
    public Binding createBinding() {
        return new Binding();
    }

    /**
     * Create an instance of {@link SuspendProcessEvent }
     * 
     */
    public SuspendProcessEvent createSuspendProcessEvent() {
        return new SuspendProcessEvent();
    }

    /**
     * Create an instance of {@link ServiceInstanceType }
     * 
     */
    public ServiceInstanceType createServiceInstanceType() {
        return new ServiceInstanceType();
    }

    /**
     * Create an instance of {@link Plugins }
     * 
     */
    public Plugins createPlugins() {
        return new Plugins();
    }

    /**
     * Create an instance of {@link Bw }
     * 
     */
    public Bw createBw() {
        return new Bw();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link NameValuePairBoolean }
     * 
     */
    public NameValuePairBoolean createNameValuePairBoolean() {
        return new NameValuePairBoolean();
    }

    /**
     * Create an instance of {@link LocalRepoInstance }
     * 
     */
    public LocalRepoInstance createLocalRepoInstance() {
        return new LocalRepoInstance();
    }

    /**
     * Create an instance of {@link Adapter }
     * 
     */
    public Adapter createAdapter() {
        return new Adapter();
    }

    /**
     * Create an instance of {@link Bwprocess }
     * 
     */
    public Bwprocess createBwprocess() {
        return new Bwprocess();
    }

    /**
     * Create an instance of {@link Checkpoints }
     * 
     */
    public Checkpoints createCheckpoints() {
        return new Checkpoints();
    }

    /**
     * Create an instance of {@link RemoteRepoInstanceType }
     * 
     */
    public RemoteRepoInstanceType createRemoteRepoInstanceType() {
        return new RemoteRepoInstanceType();
    }

    /**
     * Create an instance of {@link FormFlow }
     * 
     */
    public FormFlow createFormFlow() {
        return new FormFlow();
    }

    /**
     * Create an instance of {@link Setting.NTService }
     * 
     */
    public Setting.NTService createSettingNTService() {
        return new Setting.NTService();
    }

    /**
     * Create an instance of {@link AlertAction }
     * 
     */
    public AlertAction createAlertAction() {
        return new AlertAction();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "performPolicy")
    public JAXBElement<String> createPerformPolicy(String value) {
        return new JAXBElement<String>(_PerformPolicy_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameValuePairInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "NameValuePairInteger", substitutionHeadNamespace = "http://www.tibco.com/xmlns/ApplicationManagement", substitutionHeadName = "NVPair")
    public JAXBElement<NameValuePairInteger> createNameValuePairInteger(NameValuePairInteger value) {
        return new JAXBElement<NameValuePairInteger>(_NameValuePairInteger_QNAME, NameValuePairInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "container")
    public JAXBElement<String> createContainer(String value) {
        return new JAXBElement<String>(_Container_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "machine")
    public JAXBElement<String> createMachine(String value) {
        return new JAXBElement<String>(_Machine_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FormFlow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "formFlow", substitutionHeadNamespace = "http://www.tibco.com/xmlns/ApplicationManagement", substitutionHeadName = "baseService")
    public JAXBElement<FormFlow> createFormFlow(FormFlow value) {
        return new JAXBElement<FormFlow>(_FormFlow_QNAME, FormFlow.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HttpRepoInstance }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "httpRepoInstance", substitutionHeadNamespace = "http://www.tibco.com/xmlns/ApplicationManagement", substitutionHeadName = "remoteRepoInstance")
    public JAXBElement<HttpRepoInstance> createHttpRepoInstance(HttpRepoInstance value) {
        return new JAXBElement<HttpRepoInstance>(_HttpRepoInstance_QNAME, HttpRepoInstance.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmailAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "emailAction", substitutionHeadNamespace = "http://www.tibco.com/xmlns/ApplicationManagement", substitutionHeadName = "action")
    public JAXBElement<EmailAction> createEmailAction(EmailAction value) {
        return new JAXBElement<EmailAction>(_EmailAction_QNAME, EmailAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "action")
    public JAXBElement<ActionType> createAction(ActionType value) {
        return new JAXBElement<ActionType>(_Action_QNAME, ActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameValuePairBoolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "NameValuePairBoolean", substitutionHeadNamespace = "http://www.tibco.com/xmlns/ApplicationManagement", substitutionHeadName = "NVPair")
    public JAXBElement<NameValuePairBoolean> createNameValuePairBoolean(NameValuePairBoolean value) {
        return new JAXBElement<NameValuePairBoolean>(_NameValuePairBoolean_QNAME, NameValuePairBoolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoteRepoInstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "remoteRepoInstance")
    public JAXBElement<RemoteRepoInstanceType> createRemoteRepoInstance(RemoteRepoInstanceType value) {
        return new JAXBElement<RemoteRepoInstanceType>(_RemoteRepoInstance_QNAME, RemoteRepoInstanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "level")
    public JAXBElement<String> createLevel(String value) {
        return new JAXBElement<String>(_Level_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EventType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "event")
    public JAXBElement<EventType> createEvent(EventType value) {
        return new JAXBElement<EventType>(_Event_QNAME, EventType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Bw }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "bw", substitutionHeadNamespace = "http://www.tibco.com/xmlns/ApplicationManagement", substitutionHeadName = "baseService")
    public JAXBElement<Bw> createBw(Bw value) {
        return new JAXBElement<Bw>(_Bw_QNAME, Bw.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NVPairType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "NVPair")
    public JAXBElement<NVPairType> createNVPair(NVPairType value) {
        return new JAXBElement<NVPairType>(_NVPair_QNAME, NVPairType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FailureEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "failureEvent", substitutionHeadNamespace = "http://www.tibco.com/xmlns/ApplicationManagement", substitutionHeadName = "event")
    public JAXBElement<FailureEvent> createFailureEvent(FailureEvent value) {
        return new JAXBElement<FailureEvent>(_FailureEvent_QNAME, FailureEvent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SuspendProcessEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "suspendProcessEvent", substitutionHeadNamespace = "http://www.tibco.com/xmlns/ApplicationManagement", substitutionHeadName = "event")
    public JAXBElement<SuspendProcessEvent> createSuspendProcessEvent(SuspendProcessEvent value) {
        return new JAXBElement<SuspendProcessEvent>(_SuspendProcessEvent_QNAME, SuspendProcessEvent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "customAction", substitutionHeadNamespace = "http://www.tibco.com/xmlns/ApplicationManagement", substitutionHeadName = "action")
    public JAXBElement<CustomAction> createCustomAction(CustomAction value) {
        return new JAXBElement<CustomAction>(_CustomAction_QNAME, CustomAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Service }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "service", substitutionHeadNamespace = "http://www.tibco.com/xmlns/ApplicationManagement", substitutionHeadName = "baseService")
    public JAXBElement<Service> createService(Service value) {
        return new JAXBElement<Service>(_Service_QNAME, Service.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "checkPointRecoveryStorage", defaultValue = "false")
    public JAXBElement<Boolean> createCheckPointRecoveryStorage(Boolean value) {
        return new JAXBElement<Boolean>(_CheckPointRecoveryStorage_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "logEvent", substitutionHeadNamespace = "http://www.tibco.com/xmlns/ApplicationManagement", substitutionHeadName = "event")
    public JAXBElement<LogEvent> createLogEvent(LogEvent value) {
        return new JAXBElement<LogEvent>(_LogEvent_QNAME, LogEvent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "checkpoint")
    public JAXBElement<String> createCheckpoint(String value) {
        return new JAXBElement<String>(_Checkpoint_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Im }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "im", substitutionHeadNamespace = "http://www.tibco.com/xmlns/ApplicationManagement", substitutionHeadName = "baseService")
    public JAXBElement<Im> createIm(Im value) {
        return new JAXBElement<Im>(_Im_QNAME, Im.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Adapter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "adapter", substitutionHeadNamespace = "http://www.tibco.com/xmlns/ApplicationManagement", substitutionHeadName = "baseService")
    public JAXBElement<Adapter> createAdapter(Adapter value) {
        return new JAXBElement<Adapter>(_Adapter_QNAME, Adapter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameValuePair }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "NameValuePair", substitutionHeadNamespace = "http://www.tibco.com/xmlns/ApplicationManagement", substitutionHeadName = "NVPair")
    public JAXBElement<NameValuePair> createNameValuePair(NameValuePair value) {
        return new JAXBElement<NameValuePair>(_NameValuePair_QNAME, NameValuePair.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "baseService")
    public JAXBElement<ServiceType> createBaseService(ServiceType value) {
        return new JAXBElement<ServiceType>(_BaseService_QNAME, ServiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RvRepoInstance }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "rvRepoInstance", substitutionHeadNamespace = "http://www.tibco.com/xmlns/ApplicationManagement", substitutionHeadName = "remoteRepoInstance")
    public JAXBElement<RvRepoInstance> createRvRepoInstance(RvRepoInstance value) {
        return new JAXBElement<RvRepoInstance>(_RvRepoInstance_QNAME, RvRepoInstance.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "application")
    public JAXBElement<ApplicationType> createApplication(ApplicationType value) {
        return new JAXBElement<ApplicationType>(_Application_QNAME, ApplicationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "isFt")
    public JAXBElement<Boolean> createIsFt(Boolean value) {
        return new JAXBElement<Boolean>(_IsFt_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameValuePairPassword }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "NameValuePairPassword", substitutionHeadNamespace = "http://www.tibco.com/xmlns/ApplicationManagement", substitutionHeadName = "NVPair")
    public JAXBElement<NameValuePairPassword> createNameValuePairPassword(NameValuePairPassword value) {
        return new JAXBElement<NameValuePairPassword>(_NameValuePairPassword_QNAME, NameValuePairPassword.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocalRepoInstance }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "localRepoInstance", substitutionHeadNamespace = "http://www.tibco.com/xmlns/ApplicationManagement", substitutionHeadName = "repoInstance")
    public JAXBElement<LocalRepoInstance> createLocalRepoInstance(LocalRepoInstance value) {
        return new JAXBElement<LocalRepoInstance>(_LocalRepoInstance_QNAME, LocalRepoInstance.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RepoInstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "repoInstance")
    public JAXBElement<RepoInstanceType> createRepoInstance(RepoInstanceType value) {
        return new JAXBElement<RepoInstanceType>(_RepoInstance_QNAME, RepoInstanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "startupType", defaultValue = "automatic")
    public JAXBElement<String> createStartupType(String value) {
        return new JAXBElement<String>(_StartupType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AlertAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "alertAction", substitutionHeadNamespace = "http://www.tibco.com/xmlns/ApplicationManagement", substitutionHeadName = "action")
    public JAXBElement<AlertAction> createAlertAction(AlertAction value) {
        return new JAXBElement<AlertAction>(_AlertAction_QNAME, AlertAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/ApplicationManagement", name = "extends", scope = Plugins.class)
    public JAXBElement<AnyObject> createPluginsExtends(AnyObject value) {
        return new JAXBElement<AnyObject>(_PluginsExtends_QNAME, AnyObject.class, Plugins.class, value);
    }

}
