//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 10:11:20 AM CET 
//


package com.tibco.xmlns.applicationmanagement;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.tibco.xmlns.authentication.RequiresAuthentication;
import com.tibco.xmlns.dd.ClassLoaderExtension;
import com.tibco.xmlns.dd.CustomTSMPlugInConfiguration;
import com.tibco.xmlns.dd.DeploymentDescriptorFactory;
import com.tibco.xmlns.dd.DeploymentDescriptorType;
import com.tibco.xmlns.dd.DiffExcludeFilter;
import com.tibco.xmlns.dd.Modules;
import com.tibco.xmlns.dd.NameValuePairs;
import com.tibco.xmlns.dd.RequiredComponents;
import com.tibco.xmlns.dd.StartAsOneOf;
import com.tibco.xmlns.dd.SupportsFaultTolerance;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.tibco.com/xmlns/dd}DeploymentDescriptor" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="extends" type="{http://www.tibco.com/xmlns/ApplicationManagement}anyObject" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deploymentDescriptor",
    "_extends"
})
@XmlRootElement(name = "plugins")
public class Plugins {

    @XmlElementRef(name = "DeploymentDescriptor", namespace = "http://www.tibco.com/xmlns/dd", type = JAXBElement.class)
    protected List<JAXBElement<? extends DeploymentDescriptorType>> deploymentDescriptor;
    @XmlElementRef(name = "extends", namespace = "http://www.tibco.com/xmlns/ApplicationManagement", type = JAXBElement.class)
    protected JAXBElement<AnyObject> _extends;

    /**
     * Gets the value of the deploymentDescriptor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deploymentDescriptor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeploymentDescriptor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link DeploymentDescriptorFactory }{@code >}
     * {@link JAXBElement }{@code <}{@link Modules }{@code >}
     * {@link JAXBElement }{@code <}{@link DeploymentDescriptorType }{@code >}
     * {@link JAXBElement }{@code <}{@link StartAsOneOf }{@code >}
     * {@link JAXBElement }{@code <}{@link CustomTSMPlugInConfiguration }{@code >}
     * {@link JAXBElement }{@code <}{@link DiffExcludeFilter }{@code >}
     * {@link JAXBElement }{@code <}{@link ClassLoaderExtension }{@code >}
     * {@link JAXBElement }{@code <}{@link RequiresAuthentication }{@code >}
     * {@link JAXBElement }{@code <}{@link NameValuePairs }{@code >}
     * {@link JAXBElement }{@code <}{@link SupportsFaultTolerance }{@code >}
     * {@link JAXBElement }{@code <}{@link RequiredComponents }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends DeploymentDescriptorType>> getDeploymentDescriptor() {
        if (deploymentDescriptor == null) {
            deploymentDescriptor = new ArrayList<JAXBElement<? extends DeploymentDescriptorType>>();
        }
        return this.deploymentDescriptor;
    }

    /**
     * Gets the value of the extends property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AnyObject }{@code >}
     *     
     */
    public JAXBElement<AnyObject> getExtends() {
        return _extends;
    }

    /**
     * Sets the value of the extends property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AnyObject }{@code >}
     *     
     */
    public void setExtends(JAXBElement<AnyObject> value) {
        this._extends = ((JAXBElement<AnyObject> ) value);
    }

}
