//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 10:11:20 AM CET 
//


package com.tibco.xmlns.applicationmanagement;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.tibco.com/xmlns/ApplicationManagement}RemoteRepoInstanceType">
 *       &lt;sequence>
 *         &lt;element name="discoveryTimout" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="daemon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="service" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="network" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="regionalSubject" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="operationRetry" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "discoveryTimout",
    "daemon",
    "service",
    "network",
    "regionalSubject",
    "operationRetry"
})
public class RvRepoInstance
    extends RemoteRepoInstanceType
{

    @XmlElement(defaultValue = "5")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger discoveryTimout;
    @XmlElement(defaultValue = "tcp:7500")
    protected String daemon;
    @XmlElement(defaultValue = "7500")
    protected String service;
    protected String network;
    protected String regionalSubject;
    @XmlElement(defaultValue = "0")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger operationRetry;

    /**
     * Gets the value of the discoveryTimout property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDiscoveryTimout() {
        return discoveryTimout;
    }

    /**
     * Sets the value of the discoveryTimout property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDiscoveryTimout(BigInteger value) {
        this.discoveryTimout = value;
    }

    /**
     * Gets the value of the daemon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaemon() {
        return daemon;
    }

    /**
     * Sets the value of the daemon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaemon(String value) {
        this.daemon = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setService(String value) {
        this.service = value;
    }

    /**
     * Gets the value of the network property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetwork() {
        return network;
    }

    /**
     * Sets the value of the network property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetwork(String value) {
        this.network = value;
    }

    /**
     * Gets the value of the regionalSubject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegionalSubject() {
        return regionalSubject;
    }

    /**
     * Sets the value of the regionalSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegionalSubject(String value) {
        this.regionalSubject = value;
    }

    /**
     * Gets the value of the operationRetry property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOperationRetry() {
        return operationRetry;
    }

    /**
     * Sets the value of the operationRetry property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOperationRetry(BigInteger value) {
        this.operationRetry = value;
    }

}
