//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.03 at 10:20:18 AM CEST 
//


package com.tibco.xmlns.bw.process._2003;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tibco.xmlns.bw.process._2003 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Description_QNAME = new QName("http://xmlns.tibco.com/bw/process/2003", "description");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tibco.xmlns.bw.process._2003
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProcessDefinition }
     * 
     */
    public ProcessDefinition createProcessDefinition() {
        return new ProcessDefinition();
    }

    /**
     * Create an instance of {@link ElementSpec }
     * 
     */
    public ElementSpec createElementSpec() {
        return new ElementSpec();
    }

    /**
     * Create an instance of {@link BindingSpec }
     * 
     */
    public BindingSpec createBindingSpec() {
        return new BindingSpec();
    }

    /**
     * Create an instance of {@link ProcessDefinition.ErrorSchemas }
     * 
     */
    public ProcessDefinition.ErrorSchemas createProcessDefinitionErrorSchemas() {
        return new ProcessDefinition.ErrorSchemas();
    }

    /**
     * Create an instance of {@link ProcessDefinition.ProcessVariables }
     * 
     */
    public ProcessDefinition.ProcessVariables createProcessDefinitionProcessVariables() {
        return new ProcessDefinition.ProcessVariables();
    }

    /**
     * Create an instance of {@link Activity }
     * 
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link NamedType }
     * 
     */
    public NamedType createNamedType() {
        return new NamedType();
    }

    /**
     * Create an instance of {@link Transition }
     * 
     */
    public Transition createTransition() {
        return new Transition();
    }

    /**
     * Create an instance of {@link Label }
     * 
     */
    public Label createLabel() {
        return new Label();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.tibco.com/bw/process/2003", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

}
