//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.03 at 10:20:18 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmlns.tibco.com/bw/process/2003", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tibco.xmlns.bw.process._2003;
