//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.03 at 10:20:18 AM CEST 
//


package com.tibco.xmlns.bw.process._2003;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://xmlns.tibco.com/bw/process/2003}description" minOccurs="0"/>
 *         &lt;element name="startName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="startType" type="{http://xmlns.tibco.com/bw/process/2003}ElementSpec" minOccurs="0"/>
 *         &lt;element name="startX" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="startY" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="returnBindings" type="{http://xmlns.tibco.com/bw/process/2003}BindingSpec" minOccurs="0"/>
 *         &lt;element name="endName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="endType" type="{http://xmlns.tibco.com/bw/process/2003}ElementSpec" minOccurs="0"/>
 *         &lt;element name="endX" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="endY" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="errorSchemas" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="processVariables" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://xmlns.tibco.com/bw/process/2003}activity" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.tibco.com/bw/process/2003}transition" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.tibco.com/bw/process/2003}label" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "description",
    "startName",
    "startType",
    "startX",
    "startY",
    "returnBindings",
    "endName",
    "endType",
    "endX",
    "endY",
    "errorSchemas",
    "processVariables",
    "activity",
    "transition",
    "label"
})
@XmlRootElement(name = "ProcessDefinition")
public class ProcessDefinition {

    @XmlElement(required = true)
    protected String name;
    protected String description;
    protected String startName;
    protected ElementSpec startType;
    protected Integer startX;
    protected Integer startY;
    protected BindingSpec returnBindings;
    protected String endName;
    protected ElementSpec endType;
    protected Integer endX;
    protected Integer endY;
    protected ProcessDefinition.ErrorSchemas errorSchemas;
    protected ProcessDefinition.ProcessVariables processVariables;
    protected List<Activity> activity;
    protected List<Transition> transition;
    protected List<Label> label;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the startName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartName() {
        return startName;
    }

    /**
     * Sets the value of the startName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartName(String value) {
        this.startName = value;
    }

    /**
     * Gets the value of the startType property.
     * 
     * @return
     *     possible object is
     *     {@link ElementSpec }
     *     
     */
    public ElementSpec getStartType() {
        return startType;
    }

    /**
     * Sets the value of the startType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementSpec }
     *     
     */
    public void setStartType(ElementSpec value) {
        this.startType = value;
    }

    /**
     * Gets the value of the startX property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStartX() {
        return startX;
    }

    /**
     * Sets the value of the startX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStartX(Integer value) {
        this.startX = value;
    }

    /**
     * Gets the value of the startY property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStartY() {
        return startY;
    }

    /**
     * Sets the value of the startY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStartY(Integer value) {
        this.startY = value;
    }

    /**
     * Gets the value of the returnBindings property.
     * 
     * @return
     *     possible object is
     *     {@link BindingSpec }
     *     
     */
    public BindingSpec getReturnBindings() {
        return returnBindings;
    }

    /**
     * Sets the value of the returnBindings property.
     * 
     * @param value
     *     allowed object is
     *     {@link BindingSpec }
     *     
     */
    public void setReturnBindings(BindingSpec value) {
        this.returnBindings = value;
    }

    /**
     * Gets the value of the endName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndName() {
        return endName;
    }

    /**
     * Sets the value of the endName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndName(String value) {
        this.endName = value;
    }

    /**
     * Gets the value of the endType property.
     * 
     * @return
     *     possible object is
     *     {@link ElementSpec }
     *     
     */
    public ElementSpec getEndType() {
        return endType;
    }

    /**
     * Sets the value of the endType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementSpec }
     *     
     */
    public void setEndType(ElementSpec value) {
        this.endType = value;
    }

    /**
     * Gets the value of the endX property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEndX() {
        return endX;
    }

    /**
     * Sets the value of the endX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEndX(Integer value) {
        this.endX = value;
    }

    /**
     * Gets the value of the endY property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEndY() {
        return endY;
    }

    /**
     * Sets the value of the endY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEndY(Integer value) {
        this.endY = value;
    }

    /**
     * Gets the value of the errorSchemas property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessDefinition.ErrorSchemas }
     *     
     */
    public ProcessDefinition.ErrorSchemas getErrorSchemas() {
        return errorSchemas;
    }

    /**
     * Sets the value of the errorSchemas property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessDefinition.ErrorSchemas }
     *     
     */
    public void setErrorSchemas(ProcessDefinition.ErrorSchemas value) {
        this.errorSchemas = value;
    }

    /**
     * Gets the value of the processVariables property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessDefinition.ProcessVariables }
     *     
     */
    public ProcessDefinition.ProcessVariables getProcessVariables() {
        return processVariables;
    }

    /**
     * Sets the value of the processVariables property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessDefinition.ProcessVariables }
     *     
     */
    public void setProcessVariables(ProcessDefinition.ProcessVariables value) {
        this.processVariables = value;
    }

    /**
     * Gets the value of the activity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Activity }
     * 
     * 
     */
    public List<Activity> getActivity() {
        if (activity == null) {
            activity = new ArrayList<Activity>();
        }
        return this.activity;
    }

    /**
     * Gets the value of the transition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Transition }
     * 
     * 
     */
    public List<Transition> getTransition() {
        if (transition == null) {
            transition = new ArrayList<Transition>();
        }
        return this.transition;
    }

    /**
     * Gets the value of the label property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the label property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Label }
     * 
     * 
     */
    public List<Label> getLabel() {
        if (label == null) {
            label = new ArrayList<Label>();
        }
        return this.label;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "any"
    })
    public static class ErrorSchemas {

        @XmlAnyElement
        protected List<Element> any;

        /**
         * Gets the value of the any property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the any property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAny().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Element }
         * 
         * 
         */
        public List<Element> getAny() {
            if (any == null) {
                any = new ArrayList<Element>();
            }
            return this.any;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "any"
    })
    public static class ProcessVariables {

        @XmlAnyElement
        protected List<Element> any;

        /**
         * Gets the value of the any property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the any property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAny().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Element }
         * 
         * 
         */
        public List<Element> getAny() {
            if (any == null) {
                any = new ArrayList<Element>();
            }
            return this.any;
        }

    }

}
