//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 10:11:20 AM CET 
//


package com.tibco.xmlns.dd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.tibco.com/xmlns/dd}DeploymentDescriptorType">
 *       &lt;sequence>
 *         &lt;element name="deploymentDescriptorFactoryClassName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deploymentDescriptorXsdFileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deploymentDescriptorFactoryClassName",
    "deploymentDescriptorXsdFileName"
})
public class DeploymentDescriptorFactory
    extends DeploymentDescriptorType
{

    @XmlElement(required = true)
    protected String deploymentDescriptorFactoryClassName;
    protected String deploymentDescriptorXsdFileName;

    /**
     * Gets the value of the deploymentDescriptorFactoryClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeploymentDescriptorFactoryClassName() {
        return deploymentDescriptorFactoryClassName;
    }

    /**
     * Sets the value of the deploymentDescriptorFactoryClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeploymentDescriptorFactoryClassName(String value) {
        this.deploymentDescriptorFactoryClassName = value;
    }

    /**
     * Gets the value of the deploymentDescriptorXsdFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeploymentDescriptorXsdFileName() {
        return deploymentDescriptorXsdFileName;
    }

    /**
     * Sets the value of the deploymentDescriptorXsdFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeploymentDescriptorXsdFileName(String value) {
        this.deploymentDescriptorXsdFileName = value;
    }

}
