//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 10:11:20 AM CET 
//


package com.tibco.xmlns.dd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tibco.xmlns.dd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NameValuePairInteger_QNAME = new QName("http://www.tibco.com/xmlns/dd", "NameValuePairInteger");
    private final static QName _DiffExcludeFilter_QNAME = new QName("http://www.tibco.com/xmlns/dd", "DiffExcludeFilter");
    private final static QName _NameValuePairs_QNAME = new QName("http://www.tibco.com/xmlns/dd", "NameValuePairs");
    private final static QName _ClassLoaderExtension_QNAME = new QName("http://www.tibco.com/xmlns/dd", "ClassLoaderExtension");
    private final static QName _NVPair_QNAME = new QName("http://www.tibco.com/xmlns/dd", "NVPair");
    private final static QName _DeploymentDescriptor_QNAME = new QName("http://www.tibco.com/xmlns/dd", "DeploymentDescriptor");
    private final static QName _CustomTSMPlugInConfiguration_QNAME = new QName("http://www.tibco.com/xmlns/dd", "CustomTSMPlugInConfiguration");
    private final static QName _NameValuePairBoolean_QNAME = new QName("http://www.tibco.com/xmlns/dd", "NameValuePairBoolean");
    private final static QName _StartAsOneOf_QNAME = new QName("http://www.tibco.com/xmlns/dd", "StartAsOneOf");
    private final static QName _Modules_QNAME = new QName("http://www.tibco.com/xmlns/dd", "Modules");
    private final static QName _DeploymentDescriptorFactory_QNAME = new QName("http://www.tibco.com/xmlns/dd", "DeploymentDescriptorFactory");
    private final static QName _NameValuePair_QNAME = new QName("http://www.tibco.com/xmlns/dd", "NameValuePair");
    private final static QName _SupportsFaultTolerance_QNAME = new QName("http://www.tibco.com/xmlns/dd", "SupportsFaultTolerance");
    private final static QName _NameValuePairPassword_QNAME = new QName("http://www.tibco.com/xmlns/dd", "NameValuePairPassword");
    private final static QName _RequiredComponents_QNAME = new QName("http://www.tibco.com/xmlns/dd", "RequiredComponents");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tibco.xmlns.dd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomTSMPlugInConfiguration }
     * 
     */
    public CustomTSMPlugInConfiguration createCustomTSMPlugInConfiguration() {
        return new CustomTSMPlugInConfiguration();
    }

    /**
     * Create an instance of {@link DeploymentDescriptorType }
     * 
     */
    public DeploymentDescriptorType createDeploymentDescriptorType() {
        return new DeploymentDescriptorType();
    }

    /**
     * Create an instance of {@link ClassLoaderExtension }
     * 
     */
    public ClassLoaderExtension createClassLoaderExtension() {
        return new ClassLoaderExtension();
    }

    /**
     * Create an instance of {@link NameValuePairs }
     * 
     */
    public NameValuePairs createNameValuePairs() {
        return new NameValuePairs();
    }

    /**
     * Create an instance of {@link DiffExcludeFilter }
     * 
     */
    public DiffExcludeFilter createDiffExcludeFilter() {
        return new DiffExcludeFilter();
    }

    /**
     * Create an instance of {@link NameValuePair }
     * 
     */
    public NameValuePair createNameValuePair() {
        return new NameValuePair();
    }

    /**
     * Create an instance of {@link ComponentSoftwareReference }
     * 
     */
    public ComponentSoftwareReference createComponentSoftwareReference() {
        return new ComponentSoftwareReference();
    }

    /**
     * Create an instance of {@link NameValuePairInteger }
     * 
     */
    public NameValuePairInteger createNameValuePairInteger() {
        return new NameValuePairInteger();
    }

    /**
     * Create an instance of {@link DeploymentDescriptors }
     * 
     */
    public DeploymentDescriptors createDeploymentDescriptors() {
        return new DeploymentDescriptors();
    }

    /**
     * Create an instance of {@link RequiredComponents }
     * 
     */
    public RequiredComponents createRequiredComponents() {
        return new RequiredComponents();
    }

    /**
     * Create an instance of {@link SupportsFaultTolerance }
     * 
     */
    public SupportsFaultTolerance createSupportsFaultTolerance() {
        return new SupportsFaultTolerance();
    }

    /**
     * Create an instance of {@link NVPairType }
     * 
     */
    public NVPairType createNVPairType() {
        return new NVPairType();
    }

    /**
     * Create an instance of {@link DeploymentDescriptorFactory }
     * 
     */
    public DeploymentDescriptorFactory createDeploymentDescriptorFactory() {
        return new DeploymentDescriptorFactory();
    }

    /**
     * Create an instance of {@link NameValuePairBoolean }
     * 
     */
    public NameValuePairBoolean createNameValuePairBoolean() {
        return new NameValuePairBoolean();
    }

    /**
     * Create an instance of {@link StartAsOneOf }
     * 
     */
    public StartAsOneOf createStartAsOneOf() {
        return new StartAsOneOf();
    }

    /**
     * Create an instance of {@link Modules }
     * 
     */
    public Modules createModules() {
        return new Modules();
    }

    /**
     * Create an instance of {@link NameValuePairPassword }
     * 
     */
    public NameValuePairPassword createNameValuePairPassword() {
        return new NameValuePairPassword();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameValuePairInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/dd", name = "NameValuePairInteger", substitutionHeadNamespace = "http://www.tibco.com/xmlns/dd", substitutionHeadName = "NVPair")
    public JAXBElement<NameValuePairInteger> createNameValuePairInteger(NameValuePairInteger value) {
        return new JAXBElement<NameValuePairInteger>(_NameValuePairInteger_QNAME, NameValuePairInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DiffExcludeFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/dd", name = "DiffExcludeFilter", substitutionHeadNamespace = "http://www.tibco.com/xmlns/dd", substitutionHeadName = "DeploymentDescriptor")
    public JAXBElement<DiffExcludeFilter> createDiffExcludeFilter(DiffExcludeFilter value) {
        return new JAXBElement<DiffExcludeFilter>(_DiffExcludeFilter_QNAME, DiffExcludeFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameValuePairs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/dd", name = "NameValuePairs", substitutionHeadNamespace = "http://www.tibco.com/xmlns/dd", substitutionHeadName = "DeploymentDescriptor")
    public JAXBElement<NameValuePairs> createNameValuePairs(NameValuePairs value) {
        return new JAXBElement<NameValuePairs>(_NameValuePairs_QNAME, NameValuePairs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassLoaderExtension }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/dd", name = "ClassLoaderExtension", substitutionHeadNamespace = "http://www.tibco.com/xmlns/dd", substitutionHeadName = "DeploymentDescriptor")
    public JAXBElement<ClassLoaderExtension> createClassLoaderExtension(ClassLoaderExtension value) {
        return new JAXBElement<ClassLoaderExtension>(_ClassLoaderExtension_QNAME, ClassLoaderExtension.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NVPairType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/dd", name = "NVPair")
    public JAXBElement<NVPairType> createNVPair(NVPairType value) {
        return new JAXBElement<NVPairType>(_NVPair_QNAME, NVPairType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeploymentDescriptorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/dd", name = "DeploymentDescriptor")
    public JAXBElement<DeploymentDescriptorType> createDeploymentDescriptor(DeploymentDescriptorType value) {
        return new JAXBElement<DeploymentDescriptorType>(_DeploymentDescriptor_QNAME, DeploymentDescriptorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomTSMPlugInConfiguration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/dd", name = "CustomTSMPlugInConfiguration", substitutionHeadNamespace = "http://www.tibco.com/xmlns/dd", substitutionHeadName = "DeploymentDescriptor")
    public JAXBElement<CustomTSMPlugInConfiguration> createCustomTSMPlugInConfiguration(CustomTSMPlugInConfiguration value) {
        return new JAXBElement<CustomTSMPlugInConfiguration>(_CustomTSMPlugInConfiguration_QNAME, CustomTSMPlugInConfiguration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameValuePairBoolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/dd", name = "NameValuePairBoolean", substitutionHeadNamespace = "http://www.tibco.com/xmlns/dd", substitutionHeadName = "NVPair")
    public JAXBElement<NameValuePairBoolean> createNameValuePairBoolean(NameValuePairBoolean value) {
        return new JAXBElement<NameValuePairBoolean>(_NameValuePairBoolean_QNAME, NameValuePairBoolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StartAsOneOf }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/dd", name = "StartAsOneOf", substitutionHeadNamespace = "http://www.tibco.com/xmlns/dd", substitutionHeadName = "DeploymentDescriptor")
    public JAXBElement<StartAsOneOf> createStartAsOneOf(StartAsOneOf value) {
        return new JAXBElement<StartAsOneOf>(_StartAsOneOf_QNAME, StartAsOneOf.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Modules }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/dd", name = "Modules", substitutionHeadNamespace = "http://www.tibco.com/xmlns/dd", substitutionHeadName = "DeploymentDescriptor")
    public JAXBElement<Modules> createModules(Modules value) {
        return new JAXBElement<Modules>(_Modules_QNAME, Modules.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeploymentDescriptorFactory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/dd", name = "DeploymentDescriptorFactory", substitutionHeadNamespace = "http://www.tibco.com/xmlns/dd", substitutionHeadName = "DeploymentDescriptor")
    public JAXBElement<DeploymentDescriptorFactory> createDeploymentDescriptorFactory(DeploymentDescriptorFactory value) {
        return new JAXBElement<DeploymentDescriptorFactory>(_DeploymentDescriptorFactory_QNAME, DeploymentDescriptorFactory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameValuePair }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/dd", name = "NameValuePair", substitutionHeadNamespace = "http://www.tibco.com/xmlns/dd", substitutionHeadName = "NVPair")
    public JAXBElement<NameValuePair> createNameValuePair(NameValuePair value) {
        return new JAXBElement<NameValuePair>(_NameValuePair_QNAME, NameValuePair.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SupportsFaultTolerance }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/dd", name = "SupportsFaultTolerance", substitutionHeadNamespace = "http://www.tibco.com/xmlns/dd", substitutionHeadName = "DeploymentDescriptor")
    public JAXBElement<SupportsFaultTolerance> createSupportsFaultTolerance(SupportsFaultTolerance value) {
        return new JAXBElement<SupportsFaultTolerance>(_SupportsFaultTolerance_QNAME, SupportsFaultTolerance.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameValuePairPassword }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/dd", name = "NameValuePairPassword", substitutionHeadNamespace = "http://www.tibco.com/xmlns/dd", substitutionHeadName = "NVPair")
    public JAXBElement<NameValuePairPassword> createNameValuePairPassword(NameValuePairPassword value) {
        return new JAXBElement<NameValuePairPassword>(_NameValuePairPassword_QNAME, NameValuePairPassword.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequiredComponents }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/dd", name = "RequiredComponents", substitutionHeadNamespace = "http://www.tibco.com/xmlns/dd", substitutionHeadName = "DeploymentDescriptor")
    public JAXBElement<RequiredComponents> createRequiredComponents(RequiredComponents value) {
        return new JAXBElement<RequiredComponents>(_RequiredComponents_QNAME, RequiredComponents.class, null, value);
    }

}
